### ISSUE TITLE
Uncaught TypeError: Cannot read property '__id' of undefined

### ISSUE THREAD

**Issue by stemda** [lvarayut/relay-fullstack#103]
I just cloned the repository and the following trace shows up in the browser after running "npm install && npm start". Has anyone else had this problem?

`Uncaught TypeError: Cannot read property '__id' of undefined
    at eval (webpack:///./client/components/Footer/FooterContainer.js?:45:34)
    at classic (webpack:///./client/components/Footer/FooterContainer.js?:51:10)
    at getClassicNode (webpack:///./node_modules/react-relay/lib/RelayGraphQLTag.js?:48:20)
    at Object.getClassicFragment (webpack:///./node_modules/react-relay/lib/RelayGraphQLTag.js?:55:22)
    at Function.getFragment (webpack:///./node_modules/react-relay/lib/ReactRelayCompatContainerBuilder.js?:74:93)
    at classic (webpack:///./client/components/App/AppContainer.js?:25:53)
    at getClassicNode (webpack:///./node_modules/react-relay/lib/RelayGraphQLTag.js?:48:20)
    at Object.getClassicFragment (webpack:///./node_modules/react-relay/lib/RelayGraphQLTag.js?:55:22)
    at Function.getFragment (webpack:///./node_modules/react-relay/lib/ReactRelayCompatContainerBuilder.js?:74:93)
    at viewer (webpack:///./client/routes/ViewerQuery.js?:32:17)
    at wrappedQuery (webpack:///./node_modules/react-router-relay/es/QueryAggregator.js?:134:22)
    at buildNode (webpack:///./node_modules/react-relay/lib/buildRQL.js?:101:12)
    at Object.Query (webpack:///./node_modules/react-relay/lib/buildRQL.js?:82:16)
    at Object.instrumentedCallback [as Query] (webpack:///./node_modules/react-relay/lib/RelayProfiler.js?:130:40)
    at eval (webpack:///./node_modules/react-relay/lib/getRelayQueries.js?:61:93)
    at Array.forEach (native)
    at buildQuerySet (webpack:///./node_modules/react-relay/lib/getRelayQueries.js?:54:41)
    at getRelayQueries (webpack:///./node_modules/react-relay/lib/getRelayQueries.js?:41:18)
    at instrumentedCallback (webpack:///./node_modules/react-relay/lib/RelayProfiler.js?:130:40)
    at RelayRenderer._runQueries (webpack:///./node_modules/react-relay/lib/RelayRenderer.js?:176:92)
    at RelayRenderer.componentDidMount (webpack:///./node_modules/react-relay/lib/RelayRenderer.js?:117:10)
    at eval (webpack:///./node_modules/react-dom/lib/ReactCompositeComponent.js?:264:25)
    at measureLifeCyclePerf (webpack:///./node_modules/react-dom/lib/ReactCompositeComponent.js?:75:12)
    at eval (webpack:///./node_modules/react-dom/lib/ReactCompositeComponent.js?:263:11)
    at CallbackQueue.notifyAll (webpack:///./node_modules/react-dom/lib/CallbackQueue.js?:76:22)
    at ReactReconcileTransaction.close (webpack:///./node_modules/react-dom/lib/ReactReconcileTransaction.js?:80:26)
    at ReactReconcileTransaction.closeAll (webpack:///./node_modules/react-dom/lib/Transaction.js?:209:25)
    at ReactReconcileTransaction.perform (webpack:///./node_modules/react-dom/lib/Transaction.js?:156:16)
    at batchedMountComponentIntoNode (webpack:///./node_modules/react-dom/lib/ReactMount.js?:126:15)
    at ReactDefaultBatchingStrategyTransaction.perform (webpack:///./node_modules/react-dom/lib/Transaction.js?:143:20)
    at Object.batchedUpdates (webpack:///./node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js?:62:26)
    at Object.batchedUpdates (webpack:///./node_modules/react-dom/lib/ReactUpdates.js?:97:27)
    at Object._renderNewRootComponent (webpack:///./node_modules/react-dom/lib/ReactMount.js?:319:18)
    at Object._renderSubtreeIntoContainer (webpack:///./node_modules/react-dom/lib/ReactMount.js?:401:32)
    at Object.render (webpack:///./node_modules/react-dom/lib/ReactMount.js?:422:23)
    at render (webpack:///./client/index.js?:28:22)
    at eval (webpack:///./client/index.js?:35:1)
    at Object../client/index.js (http://localhost:3000/app.js:268:1)
    at __webpack_require__ (http://localhost:3000/vendor.js:696:30)
    at fn (http://localhost:3000/vendor.js:117:20)
    at eval (webpack:///multi_react-hot-loader/patch_./client/index.js_webpack-dev-server/client?:2:1)
    at Object.0 (http://localhost:3000/app.js:1753:1)
    at __webpack_require__ (http://localhost:3000/vendor.js:696:30)
    at webpackJsonpCallback (http://localhost:3000/vendor.js:26:23)
    at http://localhost:3000/app.js:1:1`

**UPDATE:**

Installing yo and generator-relay-fullstack globally and running the "yo relay-fullstack" command didn't lead to this issue. Everything seems to work just fine now.

**Comment by Neitsch** [comment]
Yo relay-fullstack is an outdated version. I'll try to have a look at it soon.

**Comment by stemda** [comment]
Thanks for your response @Neitsch, I'd really appreciate it. Still trying to wrap my head around the whole Relay-GraphQL stuff so I can't be of much help unfortunately.

**Comment by Neitsch** [comment]
I'm not hitting this error. Would you mind removing the node_modules and installing dependencies again? I suspect that Relay was broken.

**Comment by stemda** [comment]
Okay, after cloning the repo into a new folder everything works like a charm.  Weird, reinstalling the modules was actually one of the first things I tried when I encountered the error. Thanks again and sorry for robbing you of your time.
