### ISSUE TITLE
airbnb depends on eslint-plugin-jsx-a11y 1.2.0, 2.1.0 is provided

### ISSUE THREAD

**Issue by CDRO** [lvarayut/relay-fullstack#32]
Hello there,

first of all, thank you for your project! I really appreciate what you did here!

But...while trying to install the package as documented, the following error occured:

```
258235 error Darwin 14.5.0
258236 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
258237 error node v4.5.0
258238 error npm  v2.15.9
258239 error code EPEERINVALID
258240 error peerinvalid The package eslint-plugin-jsx-a11y@2.1.0 does not satisfy its siblings' peerDependencies requirements!
258240 error peerinvalid Peer eslint-config-airbnb@9.0.1 wants eslint-plugin-jsx-a11y@^1.2.0
258241 verbose exit [ 1, true ]
```

I figured that this should be clearly stated in the dependencies when installing the package and thus is an issue directly directed to you.

Thanks for your support and for making such a great job this far!

Greetings
Tizian

**Comment by lvarayut** [comment]
Hi Tizian, thanks for your question. This seems to be missed matched of eslint dependencies. Could you try `npm install eslint-plugin-jsx-a11y@^1.2.0`?

**Comment by CDRO** [comment]
Hello Ivarayut,

thank you for your quick feedback!

I tried this but then some other dependencies seem to not work properly too:

```
npm ERR! peerinvalid The package eslint@3.3.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-plugin-import@1.13.0 wants eslint@2.x - 3.x
npm ERR! peerinvalid Peer eslint-config-airbnb-base@5.0.3 wants eslint@^3.3.1
npm ERR! peerinvalid Peer eslint-config-airbnb@9.0.1 wants eslint@^2.9.0
```

I was wondering if this truely wasn't an npm issue, since I believed that every sub-package should be able to handle its own dependencies but it seems that I was mistaken.

Anyway

Thank you in advance
BTW: what version of npm and node.js do you use? I'm currently using npm 2.15.9 and node.js 4.5.0

Best Regards

**Comment by lvarayut** [comment]
I can install the dependencies without any problem using node `v6.3.1` and npm `3.10.3`. Could you try again with the following command:

``` sh
npm install eslint@^2.13.1 eslint-plugin-import@^1.9.2 eslint-plugin-jsx-a11y@^1.5.3 
```

**Comment by CDRO** [comment]
Thanks a lot again, this seems to do the trick, at least the application now starts.

A subsequent error is now the following:

```
relay-fullstack@1.0.0 /Users/st/scripts/relay-fullstack
├── UNMET PEER DEPENDENCY eslint@3.3.1
├── eslint-config-airbnb@9.0.1 
├── UNMET PEER DEPENDENCY eslint-plugin-jsx-a11y@2.1.0
├── eslint-plugin-react@5.2.2 
├── postcss-loader@0.10.1 
└── webpack-dev-server@1.15.0 

npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint@^2.9.0 but none was installed.
npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint-plugin-jsx-a11y@^1.2.0 but none was installed.
npm WARN eslint-config-airbnb-base@3.0.1 requires a peer of eslint@^2.9.0 but none was installed.

> relay-fullstack@1.0.0 start /Users/st/scripts/relay-fullstack
> nodemon --watch server/data/**/*.js --exec "npm run update && babel-node server/index.js"
```

This still allows the application to start, but once I call the application on port 3000, the following happens:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: w and h must be numbers
    at Jimp.throwError (/Users/st/scripts/relay-fullstack/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/jimp/index.js:82:43)
    at Jimp.contain (/Users/st/scripts/relay-fullstack/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/jimp/index.js:1751:27)
    at Object.resize (/Users/st/scripts/relay-fullstack/node_modules/favicons-webpack-plugin/node_modules/favicons/helpers-es5.js:221:27)
    at /Users/st/scripts/relay-fullstack/node_modules/favicons-webpack-plugin/node_modules/favicons/es5.js:60:41
    at fn (/Users/st/scripts/relay-fullstack/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/async/lib/async.js:746:34)
    at /Users/st/scripts/relay-fullstack/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/async/lib/async.js:1213:16
    at /Users/st/scripts/relay-fullstack/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/async/lib/async.js:166:37
    at /Users/st/scripts/relay-fullstack/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/async/lib/async.js:706:43
    at /Users/st/scripts/relay-fullstack/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/async/lib/async.js:167:37
    at Jimp.<anonymous> (/Users/st/scripts/relay-fullstack/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/async/lib/async.js:1209:30)
    at /Users/st/scripts/relay-fullstack/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/jimp/index.js:289:27
    at .<anonymous> (/Users/st/scripts/relay-fullstack/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/jimp/node_modules/pngjs/lib/png.js:74:7)
    at g (events.js:286:16)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (/Users/st/scripts/relay-fullstack/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/jimp/node_modules/pngjs/lib/png.js:36:10)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at ParserAsync._complete (/Users/st/scripts/relay-fullstack/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/jimp/node_modules/pngjs/lib/parser-async.js:109:8)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at _filter.Filter.complete (/Users/st/scripts/relay-fullstack/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/jimp/node_modules/pngjs/lib/filter-parse-async.js:19:12)
[nodemon] app crashed - waiting for file changes before starting...
```

I figured that somewhere a png file is to be generated without giving the script a width and height?

**Comment by lvarayut** [comment]
I can't reproduce the issue, I tried to use node `4.3.1` but it's still working fine on my computer 😓. However, the issue might be related to https://github.com/jantimon/favicons-webpack-plugin/issues/23.

**Comment by CDRO** [comment]
Thanks a lot for your great support! This definitely seems not te be related to your product anymore!

Closed for me!
