### ISSUE TITLE
yeoman NPM start error

### ISSUE THREAD

**Issue by ghost** [lvarayut/relay-fullstack#45]
Same error with node 6.6.0 or 4.5.0
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at Server.listen (net.js:1382:5)
    at Server.listen (/Users/SAYCalifornia/Documents/SAY-Official/sandbox/node_modules/webpack-dev-server/lib/Server.js:322:27)
    at Object.<anonymous> (/Users/SAYCalifornia/Documents/SAY-Official/sandbox/server/index.js:38:15)
    at Module._compile (module.js:409:26)
    at loader (/Users/SAYCalifornia/Documents/SAY-Official/sandbox/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js](/Users/SAYCalifornia/Documents/SAY-Official/sandbox/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at /Users/SAYCalifornia/Documents/SAY-Official/sandbox/node_modules/babel-cli/lib/_babel-node.js:159:24
    at Object.<anonymous> (/Users/SAYCalifornia/Documents/SAY-Official/sandbox/node_modules/babel-cli/lib/_babel-node.js:160:7)
    at Module._compile (module.js:409:26)
[nodemon] app crashed - waiting for file changes before starting

Thanks

**Comment by lvarayut** [comment]
Hi @SAYDigital, thanks for the question. It seems like the port `3000` has been used by another application on your machine. You could try to kill that application and run `npm start` again.

**Comment by lvarayut** [comment]
I'm going to close this issue for now. Please feel free to continue the discussion here if you had more question.
