### ISSUE TITLE
watchman installation should be included in the README instructions

### ISSUE THREAD

**Issue by eyalliebermann** [lvarayut/relay-fullstack#98]
The README instructs new users to clone install and start.
This doesn't work for those of us who have not installed watchman on their machine

## Expected Behavior

I think before the npm install, npm start phase users should be advised to verify they have watch do following the following [link](https://facebook.github.io/watchman/docs/install.html)

## Steps to Reproduce

Just follow the instructions on the current README file on a machine with no watchman
you would see the following:
```
relay-fullstack git:(master) npm start

> relay-fullstack@1.0.0 start /Users/eyalliebermann/relay-fullstack
> nodemon --watch server/data/**/*.js --exec "npm run update && npm run start-sub-task"

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: server/data/**/*.js
[nodemon] starting `npm run update && npm run start-sub-task`

> relay-fullstack@1.0.0 update /Users/eyalliebermann/relay-fullstack
> babel-node server/utils/updateSchema.js && npm run relay

Schema has been regenerated

> relay-fullstack@1.0.0 relay /Users/eyalliebermann/relay-fullstack
> relay-compiler --src ./client --schema server/data/schema.graphql

HINT: pass --watch to keep watching for changes.
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation
 instructions
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation ins
tructions
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! relay-fullstack@1.0.0 relay: `relay-compiler --src ./client --schema server/data/schema.graphql`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the relay-fullstack@1.0.0 relay script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eyalliebermann/.npm/_logs/2017-07-10T10_35_59_263Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! relay-fullstack@1.0.0 update: `babel-node server/utils/updateSchema.js && npm run relay`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the relay-fullstack@1.0.0 update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eyalliebermann/.npm/_logs/2017-07-10T10_35_59_296Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...
^C%
➜  relay-fullstack git:(master) brew update
```

**Comment by lvarayut** [comment]
Thanks @eyalliebermann for the suggestion. You're absolutely right, we need to add that to the README. A PR would be very welcomed :)

**Comment by lvarayut** [comment]
Added in https://github.com/lvarayut/relay-fullstack/commit/67d9b312b0dc9c33af96cbd44eba5ae639c3bcc7
